require 'wearable_apis/version'
require 'wearable_apis/base'
require 'wearable_apis/nokia/base'
require 'wearable_apis/nokia/health'
require 'wearable_apis/garmin/base'
require 'wearable_apis/garmin/health'
